export const API_FULL_CRYPTO_LIST = [
	{ aliases: [], name: "300 Token", symbol: "300" },
	{ aliases: [], name: "SixEleven", symbol: "611" },
	{ aliases: [], name: "808Coin", symbol: "808" },
	{ aliases: [], name: "OctoCoin", symbol: "888" },
	{ aliases: [], name: "EOS", symbol: "EOS" },
	{ aliases: [], name: "Quantstamp", symbol: "QSP" },
	{ aliases: [], name: "MonaCoin", symbol: "MONA" },
	{ aliases: [], name: "Polybius", symbol: "PLBT" },
	{ aliases: [], name: "SecureCoin", symbol: "SRC" },
	{ aliases: [], name: "BlockPay", symbol: "BLOCKPAY" },
	{ aliases: [], name: "PotCoin", symbol: "POT" },
	{ aliases: [], name: "Viacoin", symbol: "VIA" },
	{ aliases: [], name: "SACoin", symbol: "SAC" },
	{ aliases: [], name: "Simple Token", symbol: "ST" },
	{ aliases: [], name: "Oceanlab", symbol: "OCL" },
	{ aliases: [], name: "Iconomi", symbol: "ICN" },
	{ aliases: [], name: "Stellar", symbol: "XLM" },
	{ aliases: [], name: "LBRY Credits", symbol: "LBC" },
	{ aliases: [], name: "High Performa...", symbol: "HPB" },
	{ aliases: [], name: "Bitmark", symbol: "BTM2" },
	{ aliases: [], name: "APX", symbol: "APX" },
	{ aliases: [], name: "Lisk", symbol: "LSK" },
	{ aliases: [], name: "Woodcoin", symbol: "LOG" },
	{ aliases: [], name: "AirToken", symbol: "AIR" },
	{ aliases: [], name: "YENTEN", symbol: "YTN" },
	{ aliases: [], name: "Xenon", symbol: "XNN" },
	{ aliases: [], name: "NobleCoin", symbol: "NOBL" },
	{ aliases: [], name: "PopularCoin", symbol: "POP" },
	{ aliases: [], name: "Photon", symbol: "PHO" },
	{ aliases: [], name: "Solaris", symbol: "XLR" },
	{ aliases: [], name: "Primecoin", symbol: "XPM" },
	{ aliases: [], name: "Falcoin", symbol: "FAL" },
	{ aliases: [], name: "Trident Group", symbol: "TRDT" },
	{ aliases: [], name: "NautilusCoin", symbol: "NAUT" },
	{ aliases: [], name: "Publica", symbol: "PBL" },
	{ aliases: [], name: "MinexCoin", symbol: "MNX" },
	{ aliases: [], name: "iDice", symbol: "ICE" },
	{ aliases: [], name: "Regalcoin", symbol: "REC" },
	{ aliases: [], name: "Xaurum", symbol: "XAUR" },
	{ aliases: [], name: "Corethum", symbol: "CRTM" },
	{ aliases: [], name: "BumbaCoin", symbol: "BUMBA" },
	{ aliases: [], name: "Sojourn", symbol: "SOJ" },
	{ aliases: [], name: "REX", symbol: "REX" },
	{ aliases: [], name: "RevolverCoin", symbol: "XRE" },
	{ aliases: [], name: "Musicoin", symbol: "MUSIC" },
	{ aliases: [], name: "Uro", symbol: "URO" },
	{ aliases: [], name: "MiloCoin", symbol: "MILO" },
	{ aliases: [], name: "Coinlancer", symbol: "CL" },
	{ aliases: [], name: "MyWish", symbol: "WISH" },
	{ aliases: [], name: "Sling", symbol: "SLING" },
	{ aliases: [], name: "WomenCoin", symbol: "WOMEN" },
	{ aliases: [], name: "Emerald Crypto", symbol: "EMD" },
	{ aliases: [], name: "Ethorse", symbol: "HORSE" },
	{ aliases: [], name: "Destiny", symbol: "DES" },
	{ aliases: [], name: "MaxCoin", symbol: "MAX" },
	{ aliases: [], name: "ParallelCoin", symbol: "DUO" },
	{ aliases: [], name: "Evil Coin", symbol: "EVIL" },
	{ aliases: [], name: "Universal Cur...", symbol: "UNIT" },
	{ aliases: [], name: "ETHGAS", symbol: "EGAS" },
	{ aliases: [], name: "Polis", symbol: "POLIS" },
	{ aliases: [], name: "Safe Exchange...", symbol: "SAFEX" },
	{ aliases: [], symbol: "SPK" },
	{ aliases: [], name: "ZClassic", symbol: "ZCL" },
	{ aliases: [], name: "Devery", symbol: "EVE" },
	{ aliases: [], name: "AdEx", symbol: "ADX" },
	{ aliases: [], name: "LiteBitcoin", symbol: "LBTC" },
	{ aliases: [], name: "Link Platform", symbol: "LNK" },
	{ aliases: [], name: "Viuly", symbol: "VIU" },
	{ aliases: [], name: "HunterCoin", symbol: "HUC" },
	{ aliases: [], name: "ERC20", symbol: "ERC20" },
	{ aliases: [], name: "Pure", symbol: "PURE" },
	{ aliases: [], name: "Francs", symbol: "FRN" },
	{ aliases: [], name: "Carboncoin", symbol: "CARBON" },
	{ aliases: [], name: "TagCoin", symbol: "TAG" },
	{ aliases: [], name: "Dotcoin", symbol: "DOT" },
	{ aliases: [], name: "GXShares", symbol: "GXS" },
	{ aliases: [], name: "PostCoin", symbol: "POST" },
	{ aliases: [], name: "Triggers", symbol: "TRIG" },
	{ aliases: [], name: "GoldCoin", symbol: "GLD" },
	{ aliases: [], name: "Authorship", symbol: "ATS" },
	{ aliases: [], name: "IslaCoin", symbol: "ISL" },
	{ aliases: [], name: "UltraCoin", symbol: "UTC" },
	{ aliases: [], name: "Veltor", symbol: "VLT" },
	{ aliases: [], symbol: "NBT" },
	{ aliases: [], name: "Indorse Token", symbol: "IND" },
	{ aliases: [], name: "Hacken", symbol: "HKN" },
	{ aliases: [], name: "Elcoin", symbol: "EL" },
	{ aliases: [], name: "GlobalToken", symbol: "GLT" },
	{ aliases: [], name: "FinCoin", symbol: "FNC" },
	{ aliases: [], name: "E-coin", symbol: "ECN" },
	{ aliases: [], name: "Zennies", symbol: "ZENI" },
	{ aliases: [], name: "Advanced Inte...", symbol: "AIB" },
	{ aliases: [], name: "WARP", symbol: "WARP" },
	{ aliases: [], name: "Karma", symbol: "KRM" },
	{ aliases: [], name: "AurumCoin", symbol: "AU" },
	{ aliases: [], name: "Beatcoin", symbol: "XBTS" },
	{ aliases: [], name: "Tierion", symbol: "TNT" },
	{ aliases: [], name: "EventChain", symbol: "EVC" },
	{ aliases: [], name: "Bitcrystals", symbol: "BCY" },
	{ aliases: [], name: "Ethbits", symbol: "ETBS" },
	{ aliases: [], name: "Pillar", symbol: "PLR" },
	{ aliases: [], name: "Databits", symbol: "DTB" },
	{ aliases: [], name: "carVertical", symbol: "CV" },
	{ aliases: [], name: "Fastcoin", symbol: "FST" },
	{ aliases: [], name: "Cream", symbol: "CRM" },
	{ aliases: [], name: "PayPie", symbol: "PPP" },
	{ aliases: [], name: "GAIA", symbol: "GAIA" },
	{ aliases: [], name: "Grimcoin", symbol: "GRIM" },
	{ aliases: [], name: "ChessCoin", symbol: "CHESS" },
	{ aliases: [], name: "OBITS", symbol: "OBITS" },
	{ aliases: [], name: "PayCon", symbol: "CON" },
	{ aliases: [], name: "BitClave", symbol: "CAT" },
	{ aliases: [], name: "iExec RLC", symbol: "RLC" },
	{ aliases: [], symbol: "BT1" },
	{ aliases: [], name: "Civic", symbol: "CVC" },
	{ aliases: [], name: "CoinDash", symbol: "CDT" },
	{ aliases: [], name: "Komodo", symbol: "KMD" },
	{ aliases: [], name: "AmberCoin", symbol: "AMBER" },
	{ aliases: [], name: "ARbit", symbol: "ARB" },
	{ aliases: [], name: "Lampix", symbol: "PIX" },
	{ aliases: [], name: "Global Tour Coin", symbol: "GTC" },
	{ aliases: [], name: "Skeincoin", symbol: "SKC" },
	{ aliases: [], name: "ELTCOIN", symbol: "ELTCOIN" },
	{ aliases: [], name: "Starta", symbol: "STA" },
	{ aliases: [], name: "Garlicoin", symbol: "GRLC" },
	{ aliases: [], name: "DAO.Casino", symbol: "BET" },
	{ aliases: [], name: "Bolenum", symbol: "BLN" },
	{ aliases: [], name: "PX", symbol: "PX" },
	{ aliases: [], name: "Dovu", symbol: "DOVU" },
	{ aliases: [], name: "Moeda Loyalty...", symbol: "MDA" },
	{ aliases: [], name: "BuzzCoin", symbol: "BUZZ" },
	{ aliases: [], name: "Aeron", symbol: "ARN" },
	{ aliases: [], name: "Universe", symbol: "UNI" },
	{ aliases: [], name: "Joulecoin", symbol: "XJO" },
	{ aliases: [], name: "ATLANT", symbol: "ATL" },
	{ aliases: [], name: "ProCurrency", symbol: "PROC" },
	{ aliases: [], name: "SecretCoin", symbol: "SCRT" },
	{ aliases: [], name: "Gatcoin", symbol: "GAT" },
	{ aliases: [], name: "Zephyr", symbol: "ZEPH" },
	{ aliases: [], name: "Ellaism", symbol: "ELLA" },
	{ aliases: [], name: "Steem Dollars", symbol: "SBD" },
	{ aliases: [], name: "BenjiRolls", symbol: "BENJI" },
	{ aliases: [], name: "Lykke", symbol: "LKK" },
	{ aliases: [], name: "CryptCoin", symbol: "CRYPT" },
	{ aliases: [], name: "Internxt", symbol: "INXT" },
	{ aliases: [], name: "BowsCoin", symbol: "BSC" },
	{ aliases: [], name: "iCoin", symbol: "ICN2" },
	{ aliases: [], name: "Sprouts", symbol: "SPRTS" },
	{ aliases: [], name: "PoSW Coin", symbol: "POSW" },
	{ aliases: [], name: "Stealthcoin", symbol: "XST" },
	{ aliases: [], name: "Eroscoin", symbol: "ERO" },
	{ aliases: [], name: "Independent M...", symbol: "IMS" },
	{ aliases: [], name: "REAL", symbol: "REAL" },
	{ aliases: [], name: "Anoncoin", symbol: "ANC" },
	{ aliases: [], name: "BitcoinZ", symbol: "BTCZ" },
	{ aliases: [], name: "Target Coin", symbol: "TGT" },
	{ aliases: [], name: "ColossusCoinXT", symbol: "COLX" },
	{ aliases: [], name: "Mao Zedong", symbol: "MAO" },
	{ aliases: [], name: "Honey", symbol: "HONEY" },
	{ aliases: [], name: "Social Send", symbol: "SEND" },
	{ aliases: [], name: "Aragon", symbol: "ANT" },
	{ aliases: [], name: "Terracoin", symbol: "TRC" },
	{ aliases: [], name: "Devcoin", symbol: "DVC" },
	{ aliases: [], name: "Gapcoin", symbol: "GAP" },
	{ aliases: [], name: "SingularDTV", symbol: "SNGLS" },
	{ aliases: [], name: "Scorecoin", symbol: "SCORE" },
	{ aliases: [], name: "MicroMoney", symbol: "AMM" },
	{ aliases: [], name: "Presearch", symbol: "PRS" },
	{ aliases: [], name: "CorgiCoin", symbol: "CORG" },
	{ aliases: [], name: "UFO Coin", symbol: "UFO" },
	{ aliases: [], name: "Hush", symbol: "HUSH" },
	{ aliases: [], name: "Flixxo", symbol: "FLIXX" },
	{ aliases: [], name: "Colossuscoin V2", symbol: "CV2" },
	{ aliases: [], name: "Bloom", symbol: "BLT" },
	{ aliases: [], name: "MetalCoin", symbol: "METAL" },
	{ aliases: [], name: "Rasputin Onli...", symbol: "ROC" },
	{ aliases: [], name: "FlypMe", symbol: "FYP" },
	{ aliases: [], name: "TenX", symbol: "PAY" },
	{ aliases: [], name: "Dashcoin", symbol: "DSH" },
	{ aliases: [], name: "Dash", symbol: "DASH" },
	{ aliases: [], name: "CannaCoin", symbol: "CCN" },
	{ aliases: [], name: "MyBit Token", symbol: "MYB" },
	{ aliases: [], name: "Maker", symbol: "MKR" },
	{ aliases: [], name: "Interstellar ...", symbol: "HOLD" },
	{ aliases: [], name: "Bitgem", symbol: "BTG2" },
	{ aliases: [], name: "LIFE", symbol: "LIFE" },
	{ aliases: [], name: "Stox", symbol: "STX" },
	{ aliases: [], name: "UniCoin", symbol: "UNIC" },
	{ aliases: [], name: "Intelligent T...", symbol: "ITT" },
	{ aliases: [], name: "Tychocoin", symbol: "TYCHO" },
	{ aliases: [], name: "Genesis Vision", symbol: "GVT" },
	{ aliases: [], name: "Theresa May Coin", symbol: "MAY" },
	{ aliases: [], name: "Eternity", symbol: "ENT" },
	{ aliases: [], name: "ChainLink", symbol: "LINK" },
	{ aliases: [], name: "ZCoin", symbol: "XZC" },
	{ aliases: [], name: "RussiaCoin", symbol: "RC" },
	{ aliases: [], name: "Steem", symbol: "STEEM" },
	{ aliases: [], name: "Comet", symbol: "CMT" },
	{ aliases: [], name: "Circuits of V...", symbol: "COVAL" },
	{ aliases: [], name: "HTMLCOIN", symbol: "HTML" },
	{ aliases: [], name: "FIMKrypto", symbol: "FIMK" },
	{ aliases: [], name: "Ebittree Coin", symbol: "EBT" },
	{ aliases: [], name: "Kurrent", symbol: "KURT" },
	{ aliases: [], name: "RChain", symbol: "RHOC" },
	{ aliases: [], name: "Monoeci", symbol: "XMCC" },
	{ aliases: [], name: "Startcoin", symbol: "START" },
	{ aliases: [], name: "SONM", symbol: "SNM" },
	{ aliases: [], name: "Dynamic", symbol: "DYN" },
	{ aliases: [], name: "InsaneCoin", symbol: "INSN" },
	{ aliases: [], name: "Aeternity", symbol: "AE" },
	{ aliases: [], name: "Eidoo", symbol: "EDO" },
	{ aliases: [], name: "Bibox Token", symbol: "BIX" },
	{ aliases: [], name: "MustangCoin", symbol: "MST" },
	{ aliases: [], name: "Influxcoin", symbol: "INFX" },
	{ aliases: [], name: "Red Pulse", symbol: "RPX" },
	{ aliases: [], name: "Coimatic 2.0", symbol: "CTIC2" },
	{ aliases: [], name: "Ambrosus", symbol: "AMB" },
	{ aliases: [], name: "LendConnect", symbol: "LCT" },
	{ aliases: [], name: "Linda", symbol: "LINDA" },
	{ aliases: [], name: "Hawala.Today", symbol: "HAT" },
	{ aliases: [], symbol: "YYW" },
	{ aliases: [], name: "Rawcoin", symbol: "XRC" },
	{ aliases: [], name: "Sovereign Hero", symbol: "HERO" },
	{ aliases: [], symbol: "STR" },
	{ aliases: [], name: "Remicoin", symbol: "RMC2" },
	{ aliases: [], name: "CryptoPing", symbol: "PING" },
	{ aliases: [], name: "ECC", symbol: "ECC" },
	{ aliases: [], name: "Bitcloud", symbol: "BTDX" },
	{ aliases: [], name: "Ccore", symbol: "CCO" },
	{ aliases: [], name: "Hedge", symbol: "HDG" },
	{ aliases: [], name: "FunFair", symbol: "FUN" },
	{ aliases: [], name: "Rialto", symbol: "XRL" },
	{ aliases: [], name: "DubaiCoin", symbol: "DBIX" },
	{ aliases: [], name: "LevoPlus", symbol: "LVPS" },
	{ aliases: [], name: "bitEUR", symbol: "BITEUR" },
	{ aliases: [], name: "Blockpool", symbol: "BPL" },
	{ aliases: [], name: "GoldBlocks", symbol: "GB" },
	{ aliases: [], name: "FuturXe", symbol: "FXE" },
	{ aliases: [], name: "XCurrency", symbol: "XC" },
	{ aliases: [], name: "VeChain", symbol: "VEN" },
	{ aliases: [], name: "Spectrecoin", symbol: "XSPEC" },
	{ aliases: [], name: "DIBCOIN", symbol: "DIBC" },
	{ aliases: [], name: "Condensate", symbol: "RAIN" },
	{ aliases: [], name: "Revain", symbol: "R" },
	{ aliases: [], name: "Nexus", symbol: "NXS" },
	{ aliases: [], name: "aelf", symbol: "ELF" },
	{ aliases: [], name: "Propy", symbol: "PRO" },
	{ aliases: [], name: "iXledger", symbol: "IXT" },
	{ aliases: [], name: "Bitz", symbol: "BITZ" },
	{ aliases: [], name: "OKCash", symbol: "OK" },
	{ aliases: [], name: "Neuro", symbol: "NRO" },
	{ aliases: [], name: "PayCoin", symbol: "XPY" },
	{ aliases: [], name: "IntenseCoin", symbol: "ITNS" },
	{ aliases: [], name: "Bata", symbol: "BTA" },
	{ aliases: [], name: "PonziCoin", symbol: "PONZI" },
	{ aliases: [], name: "Digital Credits", symbol: "DGCS" },
	{ aliases: [], name: "Guncoin", symbol: "GUN" },
	{ aliases: [], name: "CybCSec", symbol: "XCS" },
	{ aliases: [], name: "Monero", symbol: "XMR" },
	{ aliases: [], name: "Omni", symbol: "OMNI" },
	{ aliases: [], name: "BridgeCoin", symbol: "BCO" },
	{ aliases: [], name: "Philosopher S...", symbol: "PHS" },
	{ aliases: [], name: "0x", symbol: "ZRX" },
	{ aliases: [], name: "MagicCoin", symbol: "MAGE" },
	{ aliases: [], name: "bitUSD", symbol: "BITUSD" },
	{ aliases: [], name: "Neblio", symbol: "NEBL" },
	{ aliases: [], name: "ImpulseCoin", symbol: "IMPS" },
	{ aliases: [], name: "Nimfamoney", symbol: "NIMFA" },
	{ aliases: [], name: "XPlay", symbol: "XPA" },
	{ aliases: [], name: "E-Dinar Coin", symbol: "EDR" },
	{ aliases: [], name: "Aeon", symbol: "AEON" },
	{ aliases: [], name: "Quark", symbol: "QRK" },
	{ aliases: [], name: "Voxels", symbol: "VOX" },
	{ aliases: [], name: "Verge", symbol: "XVG" },
	{ aliases: [], name: "StarCredits", symbol: "STRC" },
	{ aliases: [], name: "BigUp", symbol: "BIGUP" },
	{ aliases: [], name: "BLUE", symbol: "BLUE" },
	{ aliases: [], name: "HitCoin", symbol: "HTC" },
	{ aliases: [], name: "MobileGo", symbol: "MGO" },
	{ aliases: [], name: "GoldReserve", symbol: "XGR" },
	{ aliases: [], name: "Franko", symbol: "FRK" },
	{ aliases: [], name: "AnarchistsPrime", symbol: "ACP" },
	{ aliases: [], name: "DCORP", symbol: "DRP" },
	{ aliases: [], name: "Electra", symbol: "ECA" },
	{ aliases: [], name: "FORCE", symbol: "FOR" },
	{ aliases: [], name: "SolarCoin", symbol: "SLR" },
	{ aliases: [], name: "Everus", symbol: "EVR" },
	{ aliases: [], name: "Atmos", symbol: "ATMS" },
	{ aliases: [], name: "Darcrus", symbol: "DAR" },
	{ aliases: [], name: "CarTaxi Token", symbol: "CTX" },
	{ aliases: [], name: "Covesting", symbol: "COV" },
	{ aliases: [], name: "Ubiq", symbol: "UBQ" },
	{ aliases: [], name: "SoonCoin", symbol: "SOON" },
	{ aliases: [], name: "Slevin", symbol: "SLEVIN" },
	{ aliases: [], name: "FairCoin", symbol: "FAIR" },
	{ aliases: [], name: "Uquid Coin", symbol: "UQC" },
	{ aliases: [], name: "Zetacoin", symbol: "ZET" },
	{ aliases: [], name: "Xios", symbol: "XIOS" },
	{ aliases: [], name: "KibiCoin", symbol: "KIC" },
	{ aliases: [], name: "Bitquence", symbol: "BQX" },
	{ aliases: [], name: "Coinonat", symbol: "CXT" },
	{ aliases: [], name: "ALIS", symbol: "ALIS" },
	{ aliases: [], name: "Hshare", symbol: "HSR" },
	{ aliases: [], name: "BlakeStar", symbol: "BLAS" },
	{ aliases: [], name: "Change", symbol: "CAG" },
	{ aliases: [], name: "SwapToken", symbol: "TOKEN" },
	{ aliases: [], name: "Russian Miner...", symbol: "RMC" },
	{ aliases: [], name: "Bytecoin", symbol: "BCN" },
	{ aliases: [], name: "Rubycoin", symbol: "RBY" },
	{ aliases: [], name: "SIRIN LABS Token", symbol: "SRN" },
	{ aliases: [], name: "Iconic", symbol: "ICON" },
	{ aliases: [], name: "LoMoCoin", symbol: "LMC" },
	{ aliases: [], name: "Vcash", symbol: "XVC" },
	{ aliases: [], name: "GameUnits", symbol: "UNITS" },
	{ aliases: [], name: "Feathercoin", symbol: "FTC" },
	{ aliases: [], name: "Bitradio", symbol: "BRO" },
	{ aliases: [], name: "Suretly", symbol: "SUR" },
	{ aliases: [], name: "Crave", symbol: "CRAVE" },
	{ aliases: [], name: "Blackmoon", symbol: "BMC" },
	{ aliases: [], name: "SuperCoin", symbol: "SUPER" },
	{ aliases: [], name: "NEM", symbol: "XEM" },
	{ aliases: [], name: "Selfkey", symbol: "KEY" },
	{ aliases: [], name: "VIBE", symbol: "VIBE" },
	{ aliases: [], name: "Einsteinium", symbol: "EMC2" },
	{ aliases: [], name: "Monkey Project", symbol: "MONK" },
	{ aliases: [], name: "Paypex", symbol: "PAYX" },
	{ aliases: [], name: "Ratecoin", symbol: "XRA" },
	{ aliases: [], name: "Pirl", symbol: "PIRL" },
	{ aliases: [], name: "AntiBitcoin", symbol: "ANTI" },
	{ aliases: [], name: "SuperNET", symbol: "UNITY" },
	{ aliases: [], name: "Golem", symbol: "GNT" },
	{ aliases: [], name: "Pulse", symbol: "PULSE" },
	{ aliases: [], name: "Gulden", symbol: "NLG" },
	{ aliases: [], name: "QuazarCoin", symbol: "QCN" },
	{ aliases: [], name: "Virtacoin", symbol: "VTA" },
	{ aliases: [], name: "ZrCoin", symbol: "ZRC" },
	{ aliases: [], name: "SportyCo", symbol: "SPF" },
	{ aliases: [], name: "FuckToken", symbol: "FUCK" },
	{ aliases: [], name: "Litecred", symbol: "LTCR" },
	{ aliases: [], name: "ParkByte", symbol: "PKB" },
	{ aliases: [], name: "Evotion", symbol: "EVO" },
	{ aliases: [], name: "QASH", symbol: "QASH" },
	{ aliases: [], name: "FlavorCoin", symbol: "FLVR" },
	{ aliases: [], name: "FoldingCoin", symbol: "FLDC" },
	{ aliases: [], name: "Orlycoin", symbol: "ORLY" },
	{ aliases: [], name: "Prime-XI", symbol: "PXI" },
	{ aliases: [], name: "DigiPulse", symbol: "DGPT" },
	{ aliases: [], name: "TokenCard", symbol: "TKN" },
	{ aliases: [], name: "Soarcoin", symbol: "SOAR" },
	{ aliases: [], name: "Agoras Tokens", symbol: "AGRS" },
	{ aliases: [], name: "NodeCoin", symbol: "NODC" },
	{ aliases: [], name: "SingularityNET", symbol: "AGI" },
	{ aliases: [], name: "Netko", symbol: "NETKO" },
	{ aliases: [], name: "Sativacoin", symbol: "STV" },
	{ aliases: [], name: "Helleniccoin", symbol: "HNC" },
	{ aliases: [], name: "B3Coin", symbol: "B3" },
	{ aliases: [], name: "Capricoin", symbol: "CPC" },
	{ aliases: [], name: "Flash", symbol: "FLASH" },
	{ aliases: [], name: "HollyWoodCoin", symbol: "HWC" },
	{ aliases: [], name: "ETHLend", symbol: "LEND" },
	{ aliases: [], name: "Phoenixcoin", symbol: "PXC" },
	{ aliases: [], name: "BeaverCoin", symbol: "BVC" },
	{ aliases: [], name: "Storj", symbol: "STORJ" },
	{ aliases: [], name: "INS Ecosystem", symbol: "INS" },
	{ aliases: [], name: "Pura", symbol: "PURA" },
	{ aliases: [], symbol: "BCU" },
	{ aliases: [], name: "Oxycoin", symbol: "OXY" },
	{ aliases: [], name: "Joincoin", symbol: "J" },
	{ aliases: [], name: "Cappasity", symbol: "CAPP" },
	{ aliases: [], name: "Kolion", symbol: "KLN" },
	{ aliases: [], name: "NeuroDAO", symbol: "NDAO" },
	{ aliases: [], name: "CHNCoin", symbol: "CNC" },
	{ aliases: [], name: "PiplCoin", symbol: "PIPL" },
	{ aliases: [], name: "Auroracoin", symbol: "AUR" },
	{ aliases: [], name: "Vsync", symbol: "VSX" },
	{ aliases: [], name: "Orbitcoin", symbol: "ORB" },
	{ aliases: [], name: "Walton", symbol: "WTC" },
	{ aliases: [], name: "BlockMason Cr...", symbol: "BCPT" },
	{ aliases: [], name: "NEVERDIE", symbol: "NDC" },
	{ aliases: [], name: "Social", symbol: "SCL" },
	{ aliases: [], name: "BiosCrypto", symbol: "BIOS" },
	{ aliases: [], name: "DNotes", symbol: "NOTE" },
	{ aliases: [], name: "PosEx", symbol: "PEX" },
	{ aliases: [], name: "Speedcash", symbol: "SCS" },
	{ aliases: [], name: "LuckChain", symbol: "BASH" },
	{ aliases: [], name: "Rubies", symbol: "RBIES" },
	{ aliases: [], name: "SpaceCoin", symbol: "SPACE" },
	{ aliases: [], name: "Datum", symbol: "DAT" },
	{ aliases: [], name: "COSS", symbol: "COSS" },
	{ aliases: [], name: "YashCoin", symbol: "YASH" },
	{ aliases: [], name: "PureVidz", symbol: "VIDZ" },
	{ aliases: [], name: "HOdlcoin", symbol: "HODL" },
	{ aliases: [], name: "ATC Coin", symbol: "ATCC" },
	{ aliases: [], name: "Ecobit", symbol: "ECOB" },
	{ aliases: [], name: "Tether", symbol: "USDT" },
	{ aliases: [], name: "OsmiumCoin", symbol: "OS76" },
	{ aliases: [], name: "FedoraCoin", symbol: "TIPS" },
	{ aliases: [], name: "8Bit", symbol: "8BIT" },
	{ aliases: [], name: "ALQO", symbol: "ALQO" },
	{ aliases: [], name: "Loopring", symbol: "LRC" },
	{ aliases: [], name: "Bitcoin", symbol: "BTC" },
	{ aliases: [], name: "Enjin Coin", symbol: "ENJ" },
	{ aliases: [], name: "Yocoin", symbol: "YOC" },
	{ aliases: [], name: "bitqy", symbol: "BQ" },
	{ aliases: [], name: "Global Curren...", symbol: "GCR" },
	{ aliases: [], name: "Arcade Token", symbol: "ARC2" },
	{ aliases: [], name: "vTorrent", symbol: "VTR" },
	{ aliases: [], name: "VeriCoin", symbol: "VRC" },
	{ aliases: [], name: "PLNcoin", symbol: "PLNC" },
	{ aliases: [], name: "Project Decorum", symbol: "PDC" },
	{ aliases: [], name: "Ace", symbol: "ACE" },
	{ aliases: [], name: "Espers", symbol: "ESP" },
	{ aliases: [], name: "YOYOW", symbol: "YOYOW" },
	{ aliases: [], name: "Dimecoin", symbol: "DIME" },
	{ aliases: [], symbol: "SJCX" },
	{ aliases: [], name: "TajCoin", symbol: "TAJ" },
	{ aliases: [], name: "Spots", symbol: "SPT" },
	{ aliases: [], name: "iTicoin", symbol: "ITI" },
	{ aliases: [], name: "Torcoin", symbol: "TOR" },
	{ aliases: [], name: "DraftCoin", symbol: "DFT" },
	{ aliases: [], name: "WMCoin", symbol: "WMC" },
	{ aliases: [], name: "Binance Coin", symbol: "BNB" },
	{ aliases: [], name: "AppleCoin", symbol: "APW" },
	{ aliases: [], name: "Ethereum Gold", symbol: "ETG" },
	{ aliases: [], name: "iBank", symbol: "IBANK" },
	{ aliases: [], name: "Radium", symbol: "RADS" },
	{ aliases: [], name: "AmsterdamCoin", symbol: "AMS" },
	{ aliases: [], name: "Interzone", symbol: "ITZ" },
	{ aliases: [], name: "ATMChain", symbol: "ATM" },
	{ aliases: [], name: "Magnet", symbol: "MAG" },
	{ aliases: [], name: "Bitcurrency", symbol: "BTCR" },
	{ aliases: [], name: "PetroDollar", symbol: "XPD" },
	{ aliases: [], name: "WayGuide", symbol: "WAY" },
	{ aliases: [], name: "Litecoin", symbol: "LTC" },
	{ aliases: [], name: "DeepBrain Chain", symbol: "DBC" },
	{ aliases: [], name: "PlatinumBAR", symbol: "XPTX" },
	{ aliases: [], name: "I0Coin", symbol: "I0C" },
	{ aliases: [], name: "Riecoin", symbol: "RIC" },
	{ aliases: [], name: "Rupaya", symbol: "RUPX" },
	{ aliases: [], name: "SkinCoin", symbol: "SKIN" },
	{ aliases: [], name: "Breakout", symbol: "BRK" },
	{ aliases: [], name: "TrustPlus", symbol: "TRUST" },
	{ aliases: [], name: "Syscoin", symbol: "SYS" },
	{ aliases: [], name: "VoteCoin", symbol: "VOT" },
	{ aliases: [], name: "InPay", symbol: "INPAY" },
	{ aliases: [], name: "EthBet", symbol: "EBET" },
	{ aliases: [], name: "VeriumReserve", symbol: "VRM" },
	{ aliases: [], name: "TittieCoin", symbol: "TTC" },
	{ aliases: [], name: "TAGRcoin", symbol: "TAGR" },
	{ aliases: [], name: "ATBCoin", symbol: "ATB" },
	{ aliases: [], name: "VIP Tokens", symbol: "VIP" },
	{ aliases: [], name: "Gifto", symbol: "GTO" },
	{ aliases: [], name: "Infinitecoin", symbol: "IFC" },
	{ aliases: [], name: "GlobalCoin", symbol: "GLC" },
	{ aliases: [], name: "NewYorkCoin", symbol: "NYC" },
	{ aliases: [], name: "Linx", symbol: "LINX" },
	{ aliases: [], name: "Ripple", symbol: "XRP" },
	{ aliases: [], name: "Megacoin", symbol: "MEC" },
	{ aliases: [], name: "ReeCoin", symbol: "REE" },
	{ aliases: [], name: "Substratum", symbol: "SUB" },
	{ aliases: [], name: "Cryptonite", symbol: "XCN" },
	{ aliases: [], name: "Patientory", symbol: "PTOY" },
	{ aliases: [], name: "Dollarcoin", symbol: "DLC" },
	{ aliases: [], name: "Aion", symbol: "AION" },
	{ aliases: [], name: "Blakecoin", symbol: "BLC" },
	{ aliases: [], name: "Tigercoin", symbol: "TGC" },
	{ aliases: [], name: "ChanCoin", symbol: "CHAN" },
	{ aliases: [], name: "BTCtalkcoin", symbol: "TALK" },
	{ aliases: [], name: "AppCoins", symbol: "APPC" },
	{ aliases: [], name: "Gimli", symbol: "GIM" },
	{ aliases: [], name: "Zayedcoin", symbol: "ZYD" },
	{ aliases: [], name: "Dentacoin", symbol: "DCN" },
	{ aliases: [], name: "CasinoCoin", symbol: "CSC" },
	{ aliases: [], name: "Smoke", symbol: "SMOKE" },
	{ aliases: [], name: "Triangles", symbol: "TRI" },
	{ aliases: [], name: "Prototanium", symbol: "PR" },
	{ aliases: [], name: "SpankChain", symbol: "SPANK" },
	{ aliases: [], name: "PRIZM", symbol: "PZM" },
	{ aliases: [], name: "StarCash Network", symbol: "STARS" },
	{ aliases: [], name: "Blackstar", symbol: "BSTAR" },
	{ aliases: [], name: "Revenu", symbol: "REV" },
	{ aliases: [], name: "SophiaTX", symbol: "SPHTX" },
	{ aliases: [], name: "TransferCoin", symbol: "TX" },
	{ aliases: [], name: "Grid+", symbol: "GRID" },
	{ aliases: [], name: "Waves", symbol: "WAVES" },
	{ aliases: [], name: "FlutterCoin", symbol: "FLT" },
	{ aliases: [], name: "Ripio Credit ...", symbol: "RCN" },
	{ aliases: [], name: "GoByte", symbol: "GBX" },
	{ aliases: [], name: "Signatum", symbol: "SIGT" },
	{ aliases: [], name: "BritCoin", symbol: "BRIT" },
	{ aliases: [], name: "Etherparty", symbol: "FUEL" },
	{ aliases: [], name: "Accelerator N...", symbol: "ACC" },
	{ aliases: [], name: "Asiadigicoin", symbol: "ADCN" },
	{ aliases: [], name: "PoSToken", symbol: "POS" },
	{ aliases: [], name: "LiteCoin Ultra", symbol: "LTCU" },
	{ aliases: [], name: "Steneum Coin", symbol: "STN" },
	{ aliases: [], name: "Unify", symbol: "UNIFY" },
	{ aliases: [], name: "Wild Beast Block", symbol: "WBB" },
	{ aliases: [], name: "QunQun", symbol: "QUN" },
	{ aliases: [], name: "GameCredits", symbol: "GAME" },
	{ aliases: [], name: "Network Token", symbol: "NTWK" },
	{ aliases: [], name: "HyperStake", symbol: "HYP" },
	{ aliases: [], name: "BitBay", symbol: "BAY" },
	{ aliases: [], name: "Mineum", symbol: "MNM" },
	{ aliases: [], name: "Veros", symbol: "VRS" },
	{ aliases: [], name: "Unitus", symbol: "UIS" },
	{ aliases: [], name: "Zcash", symbol: "ZEC" },
	{ aliases: [], name: "CloakCoin", symbol: "CLOAK" },
	{ aliases: [], name: "Telcoin", symbol: "TEL" },
	{ aliases: [], name: "Mothership", symbol: "MSP" },
	{ aliases: [], name: "ExchangeN", symbol: "EXN" },
	{ aliases: [], name: "NoLimitCoin", symbol: "NLC2" },
	{ aliases: [], name: "Kronecoin", symbol: "KRONE" },
	{ aliases: [], name: "RouletteToken", symbol: "RLT" },
	{ aliases: [], name: "GeertCoin", symbol: "GEERT" },
	{ aliases: [], name: "Jewels", symbol: "JWL" },
	{ aliases: [], name: "Request Network", symbol: "REQ" },
	{ aliases: [], name: "Greencoin", symbol: "GRE" },
	{ aliases: [], name: "Memetic / Pep...", symbol: "MEME" },
	{ aliases: [], symbol: "BT2" },
	{ aliases: [], name: "Marscoin", symbol: "MARS" },
	{ aliases: [], name: "Sphere", symbol: "SPHR" },
	{ aliases: [], name: "SONO", symbol: "ALTCOM" },
	{ aliases: [], name: "Nexium", symbol: "NXC" },
	{ aliases: [], name: "Bancor", symbol: "BNT" },
	{ aliases: [], name: "Cypher", symbol: "CYP" },
	{ aliases: [], name: "Verify", symbol: "CRED" },
	{ aliases: [], name: "Sterlingcoin", symbol: "SLG" },
	{ aliases: [], name: "EuropeCoin", symbol: "ERC" },
	{ aliases: [], name: "Catcoin", symbol: "CAT2" },
	{ aliases: [], name: "HiCoin", symbol: "XHI" },
	{ aliases: [], name: "WeTrust", symbol: "TRST" },
	{ aliases: [], name: "IncaKoin", symbol: "NKA" },
	{ aliases: [], name: "Sexcoin", symbol: "SXC" },
	{ aliases: [], name: "Bounty0x", symbol: "BNTY" },
	{ aliases: [], name: "TheGCCcoin", symbol: "GCC" },
	{ aliases: [], name: "Metaverse ETP", symbol: "ETP" },
	{ aliases: [], name: "Motocoin", symbol: "MOTO" },
	{ aliases: [], name: "CryptoCarbon", symbol: "CCRB" },
	{ aliases: [], name: "SpreadCoin", symbol: "SPR" },
	{ aliases: [], name: "Altcoin", symbol: "ALT" },
	{ aliases: [], name: "Metal", symbol: "MTL" },
	{ aliases: [], name: "Stakecoin", symbol: "STCN" },
	{ aliases: [], name: "Qbic", symbol: "QBIC" },
	{ aliases: [], name: "Cannation", symbol: "CNNC" },
	{ aliases: [], name: "BOAT", symbol: "BOAT" },
	{ aliases: [], name: "Chronologic", symbol: "DAY" },
	{ aliases: [], name: "Shadow Token", symbol: "SHDW" },
	{ aliases: [], name: "Mercury Protocol", symbol: "GMT" },
	{ aliases: [], name: "Bitcore", symbol: "BTX2" },
	{ aliases: [], name: "Cryptojacks", symbol: "CJ" },
	{ aliases: [], name: "Acoin", symbol: "ACOIN" },
	{ aliases: [], name: "Everex", symbol: "EVX" },
	{ aliases: [], name: "Open Trading ...", symbol: "OTN" },
	{ aliases: [], name: "Eurocoin", symbol: "EUC" },
	{ aliases: [], name: "CrowdCoin", symbol: "CRC" },
	{ aliases: [], name: "Firecoin", symbol: "FIRE" },
	{ aliases: [], name: "Cryptopay", symbol: "CPAY" },
	{ aliases: [], name: "Xonecoin", symbol: "XOC" },
	{ aliases: [], name: "Obsidian", symbol: "ODN" },
	{ aliases: [], name: "Snovio", symbol: "SNOV" },
	{ aliases: [], name: "Ethereum Classic", symbol: "ETC" },
	{ aliases: [], name: "BillaryCoin", symbol: "BLRY" },
	{ aliases: [], name: "OP Coin", symbol: "OPC" },
	{ aliases: [], name: "Credo", symbol: "CREDO" },
	{ aliases: [], name: "TOKYO", symbol: "TOKC" },
	{ aliases: [], name: "Adelphoi", symbol: "ADL" },
	{ aliases: [], name: "Digitalcoin", symbol: "DGC" },
	{ aliases: [], name: "Mintcoin", symbol: "MINT" },
	{ aliases: [], name: "ArtByte", symbol: "ABY" },
	{ aliases: [], name: "LeaCoin", symbol: "LEA" },
	{ aliases: [], name: "Playkey", symbol: "PKT" },
	{ aliases: [], symbol: "QSH" },
	{ aliases: [], name: "ICO OpenLedger", symbol: "ICOO" },
	{ aliases: [], name: "Dogecoin", symbol: "DOGE" },
	{ aliases: [], name: "Experience Po...", symbol: "XP" },
	{ aliases: [], name: "SproutsExtreme", symbol: "SPEX" },
	{ aliases: [], name: "Rimbit", symbol: "RBT" },
	{ aliases: [], name: "Madcoin", symbol: "MDC" },
	{ aliases: [], name: "Canada eCoin", symbol: "CDN" },
	{ aliases: [], name: "BlackCoin", symbol: "BLK" },
	{ aliases: [], name: "Compcoin", symbol: "CMP" },
	{ aliases: [], name: "Dragonchain", symbol: "DRGN" },
	{ aliases: [], name: "Qwark", symbol: "QWARK" },
	{ aliases: [], name: "ShadowCash", symbol: "SDC" },
	{ aliases: [], name: "Time New Bank", symbol: "TNB" },
	{ aliases: [], name: "DEW", symbol: "DEW" },
	{ aliases: [], name: "DFSCoin", symbol: "DFS" },
	{ aliases: [], name: "FlorinCoin", symbol: "FLO" },
	{ aliases: [], name: "PinkCoin", symbol: "PINK" },
	{ aliases: [], name: "WhiteCoin", symbol: "XWC" },
	{ aliases: [], name: "Slimcoin", symbol: "SLM" },
	{ aliases: [], name: "Achain", symbol: "ACT" },
	{ aliases: [], name: "Dent", symbol: "DENT" },
	{ aliases: [], name: "Pioneer Coin", symbol: "PCOIN" },
	{ aliases: [], name: "Oyster", symbol: "PRL" },
	{ aliases: [], name: "Bitcoin Gold", symbol: "BTG" },
	{ aliases: [], name: "Internet Node...", symbol: "INT" },
	{ aliases: [], name: "Dynamic Tradi...", symbol: "DTR" },
	{ aliases: [], name: "Save and Gain", symbol: "SANDG" },
	{ aliases: [], name: "Ormeus Coin", symbol: "ORME" },
	{ aliases: [], name: "Siacoin", symbol: "SC" },
	{ aliases: [], name: "eREAL", symbol: "EREAL" },
	{ aliases: [], name: "Stratis", symbol: "STRAT" },
	{ aliases: [], name: "Voise", symbol: "VOISE" },
	{ aliases: [], name: "AICHAIN", symbol: "AIT" },
	{ aliases: [], name: "GET Protocol", symbol: "GET" },
	{ aliases: [], name: "Growers Inter...", symbol: "GRWI" },
	{ aliases: [], name: "Zlancer", symbol: "ZCG" },
	{ aliases: [], name: "Piggycoin", symbol: "PIGGY" },
	{ aliases: [], name: "Starbase", symbol: "STAR" },
	{ aliases: [], name: "Qbao", symbol: "QBT" },
	{ aliases: [], name: "AquariusCoin", symbol: "ARCO" },
	{ aliases: [], name: "Casino", symbol: "CASINO" },
	{ aliases: [], name: "ChainCoin", symbol: "CHC" },
	{ aliases: [], name: "Kubera Coin", symbol: "KBR" },
	{ aliases: [], name: "Zonecoin", symbol: "ZNE" },
	{ aliases: [], name: "Blitzcash", symbol: "BLITZ" },
	{ aliases: [], name: "SOILcoin", symbol: "SOIL" },
	{ aliases: [], name: "Creatio", symbol: "XCRE" },
	{ aliases: [], name: "SIBCoin", symbol: "SIB" },
	{ aliases: [], name: "ZoZoCoin", symbol: "ZZC" },
	{ aliases: [], name: "Kayicoin", symbol: "KAYI" },
	{ aliases: [], name: "NeosCoin", symbol: "NEOS" },
	{ aliases: [], name: "CacheCoin", symbol: "CACH" },
	{ aliases: [], name: "Po.et", symbol: "POE" },
	{ aliases: [], name: "Ride My Car", symbol: "RIDE" },
	{ aliases: [], symbol: "MNA" },
	{ aliases: [], name: "SocialCoin", symbol: "SOCC" },
	{ aliases: [], name: "Paragon", symbol: "PRG" },
	{ aliases: [], symbol: "QTM" },
	{ aliases: [], name: "Cofound.it", symbol: "CFI" },
	{ aliases: [], name: "Cobinhood", symbol: "COB" },
	{ aliases: [], symbol: "EUR" },
	{ aliases: [], name: "QLINK", symbol: "QLC" },
	{ aliases: [], name: "Bonpay", symbol: "BON" },
	{ aliases: [], name: "Upfiring", symbol: "UFR" },
	{ aliases: [], name: "eBoost", symbol: "EBST" },
	{ aliases: [], name: "DigitalDevelo...", symbol: "DDF" },
	{ aliases: [], name: "ION", symbol: "ION" },
	{ aliases: [], name: "Braincoin", symbol: "BRAIN" },
	{ aliases: [], name: "AllSafe", symbol: "ASAFE2" },
	{ aliases: [], name: "Numeraire", symbol: "NMR" },
	{ aliases: [], name: "Wyvern", symbol: "WYV" },
	{ aliases: [], name: "indaHash", symbol: "IDH" },
	{ aliases: [], name: "EncrypGen", symbol: "DNA" },
	{ aliases: [], name: "Commodity Ad ...", symbol: "CDX" },
	{ aliases: [], name: "NuBits", symbol: "USNBT" },
	{ aliases: [], name: "Bulwark", symbol: "BWK" },
	{ aliases: [], name: "ReddCoin", symbol: "RDD" },
	{ aliases: [], name: "Ethereum Movi...", symbol: "EMV" },
	{ aliases: [], name: "Decentraland", symbol: "MANA" },
	{ aliases: [], name: "BigBoobsCoin", symbol: "BBC" },
	{ aliases: [], name: "Phore", symbol: "PHR" },
	{ aliases: [], name: "bitSilver", symbol: "BITSILVER" },
	{ aliases: [], name: "Swarm City", symbol: "SWT" },
	{ aliases: [], name: "C-Bit", symbol: "XCT" },
	{ aliases: [], symbol: "CAD" },
	{ aliases: [], name: "CanYaCoin", symbol: "CAN" },
	{ aliases: [], name: "Leverj", symbol: "LEV" },
	{ aliases: [], name: "Pandacoin", symbol: "PND" },
	{ aliases: [], name: "MojoCoin", symbol: "MOJO" },
	{ aliases: [], name: "BipCoin", symbol: "BIP" },
	{ aliases: [], name: "RSGPcoin", symbol: "RSGP" },
	{ aliases: [], name: "BnrtxCoin", symbol: "BNX" },
	{ aliases: [], name: "Factom", symbol: "FCT" },
	{ aliases: [], name: "Namecoin", symbol: "NMC" },
	{ aliases: [], name: "EagleCoin", symbol: "EAGLE" },
	{ aliases: [], name: "Impact", symbol: "IMX" },
	{ aliases: [], name: "DigitalPrice", symbol: "DP" },
	{ aliases: [], name: "Clams", symbol: "CLAM" },
	{ aliases: [], name: "Credence Coin", symbol: "CRDNC" },
	{ aliases: [], name: "Magi", symbol: "XMG" },
	{ aliases: [], name: "Litecoin Plus", symbol: "LCP" },
	{ aliases: [], name: "Matchpool", symbol: "GUP" },
	{ aliases: [], name: "Flaxscript", symbol: "FLAX" },
	{ aliases: [], name: "KiloCoin", symbol: "KLC" },
	{ aliases: [], name: "Frazcoin", symbol: "FRAZ" },
	{ aliases: [], name: "OriginTrail", symbol: "TRAC" },
	{ aliases: [], name: "Crystal Clear", symbol: "CCT" },
	{ aliases: [], name: "Spectre.ai Ut...", symbol: "SXUT" },
	{ aliases: [], name: "SagaCoin", symbol: "SAGA" },
	{ aliases: [], name: "Dai", symbol: "DAI" },
	{ aliases: [], name: "InvestFeed", symbol: "IFT" },
	{ aliases: [], name: "LiteDoge", symbol: "LDOGE" },
	{ aliases: [], name: "Veritaseum", symbol: "VERI" },
	{ aliases: [], name: "Delphy", symbol: "DPY" },
	{ aliases: [], name: "ClearPoll", symbol: "POLL" },
	{ aliases: [], name: "EquiTrader", symbol: "EQT" },
	{ aliases: [], name: "HEAT", symbol: "HEAT" },
	{ aliases: [], name: "CoinonatX", symbol: "XCXT" },
	{ aliases: [], name: "Viberate", symbol: "VIB" },
	{ aliases: [], name: "Bitcoin Plus", symbol: "XBC" },
	{ aliases: [], name: "BitBoost", symbol: "BBT" },
	{ aliases: [], name: "Flycoin", symbol: "FLY" },
	{ aliases: [], name: "Bottlecaps", symbol: "CAP" },
	{ aliases: [], name: "Pesobit", symbol: "PSB" },
	{ aliases: [], name: "Dix Asset", symbol: "DIX" },
	{ aliases: [], name: "Bitcoin Planet", symbol: "BTPL" },
	{ aliases: [], name: "AgrolifeCoin", symbol: "AGLC" },
	{ aliases: [], name: "KingN Coin", symbol: "KNC2" },
	{ aliases: [], name: "TRON", symbol: "TRX" },
	{ aliases: [], name: "Emercoin", symbol: "EMC" },
	{ aliases: [], name: "DAS", symbol: "DAS" },
	{ aliases: [], name: "GBCGoldCoin", symbol: "GBC" },
	{ aliases: [], name: "Pascal Lite", symbol: "PASL" },
	{ aliases: [], name: "WhaleCoin", symbol: "WHL" },
	{ aliases: [], name: "Unity Ingot", symbol: "UNY" },
	{ aliases: [], name: "WorldCoin", symbol: "WDC" },
	{ aliases: [], name: "Raiden Networ...", symbol: "RDN" },
	{ aliases: [], name: "Steps", symbol: "STEPS" },
	{ aliases: [], name: "Byteball Bytes", symbol: "GBYTE" },
	{ aliases: [], name: "LetItRide", symbol: "LIR" },
	{ aliases: [], name: "Crypto", symbol: "CTO" },
	{ aliases: [], name: "Enigma", symbol: "ENG" },
	{ aliases: [], name: "Santiment Net...", symbol: "SAN" },
	{ aliases: [], name: "Aricoin", symbol: "ARI" },
	{ aliases: [], name: "Stress", symbol: "STS" },
	{ aliases: [], name: "Freicoin", symbol: "FRC" },
	{ aliases: [], name: "Bismuth", symbol: "BIS" },
	{ aliases: [], name: "Valorbit", symbol: "VAL" },
	{ aliases: [], name: "Bitcoin Fast", symbol: "BCF" },
	{ aliases: [], name: "Eryllium", symbol: "ERY" },
	{ aliases: [], name: "Giga Watt Token", symbol: "WTT" },
	{ aliases: [], name: "Shilling", symbol: "SH" },
	{ aliases: [], name: "Cashcoin", symbol: "CASH" },
	{ aliases: [], name: "Vertcoin", symbol: "VTC" },
	{ aliases: [], name: "SwagBucks", symbol: "BUCKS" },
	{ aliases: [], name: "Renos", symbol: "RNS" },
	{ aliases: [], name: "Aigang", symbol: "AIX" },
	{ aliases: [], name: "B2B", symbol: "B2B" },
	{ aliases: [], name: "BitCoal", symbol: "COAL" },
	{ aliases: [], name: "Rupee", symbol: "RUP" },
	{ aliases: [], name: "Tattoocoin (S...", symbol: "TSE" },
	{ aliases: [], name: "DeepOnion", symbol: "ONION" },
	{ aliases: [], name: "CryptoInsight", symbol: "TKR" },
	{ aliases: [], name: "Master Swiscoin", symbol: "MSCN" },
	{ aliases: [], name: "Wild Crypto", symbol: "WILD" },
	{ aliases: [], name: "HempCoin", symbol: "HMP" },
	{ aliases: [], name: "Hexx", symbol: "HXX" },
	{ aliases: [], name: "adToken", symbol: "ADT" },
	{ aliases: [], name: "Mutual Coin", symbol: "MUT" },
	{ aliases: [], name: "Adzcoin", symbol: "ADZ" },
	{ aliases: [], name: "Ergo", symbol: "EFYT" },
	{ aliases: [], name: "Coin2.1", symbol: "C2" },
	{ aliases: [], name: "KushCoin", symbol: "KUSH" },
	{ aliases: [], name: "Gas", symbol: "GAS" },
	{ aliases: [], name: "Marijuanacoin", symbol: "MAR" },
	{ aliases: [], name: "VeChain", symbol: "VET" },
	{ aliases: [], name: "Bitland", symbol: "CADASTRAL" },
	{ aliases: [], name: "Bit20", symbol: "BTWTY" },
	{ aliases: [], name: "Masternodecoin", symbol: "MTNC" },
	{ aliases: [], name: "Mercury", symbol: "MER" },
	{ aliases: [], name: "Tao", symbol: "XTO" },
	{ aliases: [], name: "DomRaider", symbol: "DRT" },
	{ aliases: [], name: "Machinecoin", symbol: "MAC" },
	{ aliases: [], name: "Blocknet", symbol: "BLOCK" },
	{ aliases: [], name: "Exchange Union", symbol: "XUC" },
	{ aliases: [], name: "BitBar", symbol: "BTB" },
	{ aliases: [], name: "Ink", symbol: "INK" },
	{ aliases: [], name: "TEKcoin", symbol: "TEK" },
	{ aliases: [], name: "Useless Ether...", symbol: "UET" },
	{ aliases: [], name: "Truckcoin", symbol: "TRK" },
	{ aliases: [], name: "ProChain", symbol: "PRA" },
	{ aliases: [], name: "EMoneyPower", symbol: "EMP" },
	{ aliases: [], name: "ZetaMicron", symbol: "ZMC" },
	{ aliases: [], name: "Desire", symbol: "DSR" },
	{ aliases: [], name: "MindCoin", symbol: "MND" },
	{ aliases: [], name: "Zilliqa", symbol: "ZIL" },
	{ aliases: [], name: "Mysterium", symbol: "MYST" },
	{ aliases: [], name: "Astro", symbol: "ASTRO" },
	{ aliases: [], name: "JIO Token", symbol: "JIO" },
	{ aliases: [], name: "Selfiecoin", symbol: "SLFI" },
	{ aliases: [], name: "Aurora DAO", symbol: "AURA" },
	{ aliases: [], name: "Divi", symbol: "DIVX" },
	{ aliases: [], name: "Sequence", symbol: "SEQ" },
	{ aliases: [], name: "Bitcoin 21", symbol: "XBTC21" },
	{ aliases: [], name: "LottoCoin", symbol: "LOT" },
	{ aliases: [], name: "BitAsean", symbol: "BAS" },
	{ aliases: [], name: "Burst", symbol: "BURST" },
	{ aliases: [], name: "Nyancoin", symbol: "NYAN" },
	{ aliases: [], name: "CRTCoin", symbol: "CRT" },
	{ aliases: [], name: "PACcoin", symbol: "PAC" },
	{ aliases: [], name: "Jin Coin", symbol: "JIN" },
	{ aliases: [], name: "Sugar Exchange", symbol: "SGR" },
	{ aliases: [], name: "CampusCoin", symbol: "CMPCO" },
	{ aliases: [], name: "Nebulas", symbol: "NAS" },
	{ aliases: [], name: "Bitcoin Scrypt", symbol: "BTCS" },
	{ aliases: [], name: "TeslaCoin", symbol: "TES" },
	{ aliases: [], name: "MorningStar", symbol: "MRNG" },
	{ aliases: [], name: "Copico", symbol: "XCPO" },
	{ aliases: [], name: "Cindicator", symbol: "CND" },
	{ aliases: [], name: "STRAKS", symbol: "STAK" },
	{ aliases: [], name: "Energo", symbol: "TSL" },
	{ aliases: [], name: "OracleChain", symbol: "OCT" },
	{ aliases: [], name: "FundYourselfNow", symbol: "FYN" },
	{ aliases: [], name: "Bytecent", symbol: "BYC" },
	{ aliases: [], name: "HelloGold", symbol: "HGT" },
	{ aliases: [], name: "ICOBID", symbol: "ICOB" },
	{ aliases: [], name: "EcoCoin", symbol: "ECO" },
	{ aliases: [], name: "Hackspace Cap...", symbol: "HAC" },
	{ aliases: [], symbol: "XDG" },
	{ aliases: [], name: "Payfair", symbol: "PFR" },
	{ aliases: [], name: "Cardano", symbol: "ADA" },
	{ aliases: [], name: "NEO", symbol: "NEO" },
	{ aliases: [], name: "Gambit", symbol: "GAM" },
	{ aliases: [], name: "Roofs", symbol: "ROOFS" },
	{ aliases: [], name: "Peercoin", symbol: "PPC" },
	{ aliases: [], name: "ICON", symbol: "ICX" },
	{ aliases: [], name: "Pesetacoin", symbol: "PTC" },
	{ aliases: [], name: "ToaCoin", symbol: "TOA" },
	{ aliases: [], name: "MediShares", symbol: "MDS" },
	{ aliases: [], name: "MCAP", symbol: "MCAP" },
	{ aliases: [], name: "TrumpCoin", symbol: "TRUMP" },
	{ aliases: [], name: "Power Ledger", symbol: "POWR" },
	{ aliases: [], name: "Debitcoin", symbol: "DBTC" },
	{ aliases: [], name: "Dinastycoin", symbol: "DCY" },
	{ aliases: [], name: "Bitvolt", symbol: "VOLT" },
	{ aliases: [], name: "Deutsche eMark", symbol: "DEM" },
	{ aliases: [], name: "Quantum", symbol: "QAU" },
	{ aliases: [], name: "EOT Token", symbol: "EOT" },
	{ aliases: [], name: "DECENT", symbol: "DCT" },
	{ aliases: [], name: "DaxxCoin", symbol: "DAXX" },
	{ aliases: [], name: "e-Gulden", symbol: "EFL" },
	{ aliases: [], name: "Gold Pressed ...", symbol: "GPL" },
	{ aliases: [], name: "Syndicate", symbol: "SYNX" },
	{ aliases: [], name: "Hubii Network", symbol: "HBT" },
	{ aliases: [], name: "BitTokens", symbol: "BXT" },
	{ aliases: [], name: "Dollar Online", symbol: "DOLLAR" },
	{ aliases: [], name: "Groestlcoin", symbol: "GRS" },
	{ aliases: [], name: "Streamr DATAcoin", symbol: "DATA" },
	{ aliases: [], name: "Jinn", symbol: "JINN" },
	{ aliases: [], name: "Etheriya", symbol: "RIYA" },
	{ aliases: [], name: "bitCNY", symbol: "BITCNY" },
	{ aliases: [], name: "eBitcoin", symbol: "EBTC" },
	{ aliases: [], name: "OmiseGO", symbol: "OMG" },
	{ aliases: [], name: "LAToken", symbol: "LA" },
	{ aliases: [], name: "NAV Coin", symbol: "NAV" },
	{ aliases: [], name: "Decision Token", symbol: "HST" },
	{ aliases: [], name: "GlobalBoost-Y", symbol: "BSTY" },
	{ aliases: [], name: "Grantcoin", symbol: "GRT" },
	{ aliases: [], name: "SongCoin", symbol: "SONG" },
	{ aliases: [], name: "Diamond", symbol: "DMD" },
	{ aliases: [], name: "Curecoin", symbol: "CURE" },
	{ aliases: [], name: "DigiByte", symbol: "DGB" },
	{ aliases: [], name: "Primalbase Token", symbol: "PBT" },
	{ aliases: [], name: "Soma", symbol: "SCT" },
	{ aliases: [], name: "Shorty", symbol: "SHORTY" },
	{ aliases: [], name: "CryptoForecast", symbol: "CFT" },
	{ aliases: [], name: "CryptoWorldX ...", symbol: "CWXT" },
	{ aliases: [], name: "bitGold", symbol: "BITGOLD" },
	{ aliases: [], name: "Zeitcoin", symbol: "ZEIT" },
	{ aliases: [], name: "QubitCoin", symbol: "Q2C" },
	{ aliases: [], name: "Kobocoin", symbol: "KOBO" },
	{ aliases: [], name: "Ultimate Secu...", symbol: "USC" },
	{ aliases: [], name: "Vault Coin", symbol: "VLTC" },
	{ aliases: [], name: "Unikoin Gold", symbol: "UKG" },
	{ aliases: [], name: "Lamden", symbol: "TAU" },
	{ aliases: [], name: "WavesGo", symbol: "WGO" },
	{ aliases: [], name: "Dalecoin", symbol: "DALC" },
	{ aliases: [], name: "Ethereum", symbol: "ETH" },
	{ aliases: [], name: "MTMGaming", symbol: "MTM" },
	{ aliases: [], name: "GridCoin", symbol: "GRC" },
	{ aliases: [], name: "Pepe Cash", symbol: "PEPECASH" },
	{ aliases: [], name: "Modum", symbol: "MOD" },
	{ aliases: [], name: "RonPaulCoin", symbol: "RPC" },
	{ aliases: [], name: "Jetcoin", symbol: "JET" },
	{ aliases: [], name: "VapersCoin", symbol: "VPRC" },
	{ aliases: [], name: "Pakcoin", symbol: "PAK" },
	{ aliases: [], symbol: "GBP" },
	{ aliases: [], name: "Ethos", symbol: "ETHOS" },
	{ aliases: [], name: "DAPPSTER", symbol: "DLISK" },
	{ aliases: [], name: "Centra", symbol: "CTR" },
	{ aliases: [], name: "BiblePay", symbol: "BBP" },
	{ aliases: [], name: "Peerplays", symbol: "PPY" },
	{ aliases: [], name: "MarteXcoin", symbol: "MXT" },
	{ aliases: [], name: "CoExistCoin", symbol: "COXST" },
	{ aliases: [], name: "Janus", symbol: "JNS" },
	{ aliases: [], name: "Ardor", symbol: "ARDR" },
	{ aliases: [], name: "Billionaire T...", symbol: "XBL" },
	{ aliases: [], name: "BCAP", symbol: "BCAP" },
	{ aliases: [], name: "SwftCoin", symbol: "SWFTC" },
	{ aliases: [], name: "Zurcoin", symbol: "ZUR" },
	{ aliases: [], name: "Maecenas", symbol: "ART" },
	{ aliases: [], name: "Presearch", symbol: "PRE" },
	{ aliases: [], name: "Privatix", symbol: "PRIX" },
	{ aliases: [], name: "Humaniq", symbol: "HMQ" },
	{ aliases: [], name: "Magnum", symbol: "MGM" },
	{ aliases: [], name: "VectorAI", symbol: "VEC2" },
	{ aliases: [], name: "HarmonyCoin", symbol: "HMC" },
	{ aliases: [], name: "UnbreakableCoin", symbol: "UNB" },
	{ aliases: [], name: "XTRABYTES", symbol: "XBY" },
	{ aliases: [], name: "Blocktix", symbol: "TIX" },
	{ aliases: [], name: "BlueCoin", symbol: "BLU" },
	{ aliases: [], name: "KekCoin", symbol: "KEK" },
	{ aliases: [], name: "Monaco", symbol: "MCO" },
	{ aliases: [], name: "KickCoin", symbol: "KICK" },
	{ aliases: [], name: "Spectre.ai Di...", symbol: "SXDT" },
	{ aliases: [], name: "Cryptonex", symbol: "CNX" },
	{ aliases: [], name: "ExclusiveCoin", symbol: "EXCL" },
	{ aliases: [], name: "Quatloo", symbol: "QTL" },
	{ aliases: [], name: "NAGA", symbol: "NGC" },
	{ aliases: [], name: "GCN Coin", symbol: "GCN" },
	{ aliases: [], name: "Digital Money...", symbol: "DMB" },
	{ aliases: [], name: "Myriad", symbol: "XMY" },
	{ aliases: [], name: "CVCoin", symbol: "CVCOIN" },
	{ aliases: [], name: "HoboNickels", symbol: "HBN" },
	{ aliases: [], name: "Bean Cash", symbol: "BITB" },
	{ aliases: [], name: "Version", symbol: "V" },
	{ aliases: [], name: "MaidSafeCoin", symbol: "MAID" },
	{ aliases: [], name: "CHIPS", symbol: "CHIPS" },
	{ aliases: [], name: "Bitpark Coin", symbol: "BPC" },
	{ aliases: [], name: "Zoin", symbol: "ZOI" },
	{ aliases: [], name: "Nano", symbol: "XRB" },
	{ aliases: [], name: "IOStoken", symbol: "IOST" },
	{ aliases: [], name: "Yacoin", symbol: "YAC" },
	{ aliases: [], name: "vSlice", symbol: "VSL" },
	{ aliases: [], name: "Storm", symbol: "STORM" },
	{ aliases: [], name: "OneRoot Network", symbol: "RNT" },
	{ aliases: [], name: "Decred", symbol: "DCR" },
	{ aliases: [], name: "Elysium", symbol: "ELS" },
	{ aliases: [], name: "Dreamcoin", symbol: "DRM" },
	{ aliases: [], name: "SALT", symbol: "SALT" },
	{ aliases: [], name: "Edgeless", symbol: "EDG" },
	{ aliases: [], name: "OHM", symbol: "OHM" },
	{ aliases: [], name: "USDe", symbol: "USDE" },
	{ aliases: [], name: "BitcoinDark", symbol: "BTCD" },
	{ aliases: [], name: "Blockport", symbol: "BPT" },
	{ aliases: [], name: "LockChain", symbol: "LOC" },
	{ aliases: [], name: "VIVO", symbol: "VIVO" },
	{ aliases: [], name: "Virta Unique ...", symbol: "VUC" },
	{ aliases: [], name: "WaBi", symbol: "WABI" },
	{ aliases: [], name: "GanjaCoin", symbol: "MRJA" },
	{ aliases: [], name: "PutinCoin", symbol: "PUT" },
	{ aliases: [], name: "Opus", symbol: "OPT" },
	{ aliases: [], name: "Concoin", symbol: "CONX" },
	{ aliases: [], name: "Quantum Resis...", symbol: "QRL" },
	{ aliases: [], name: "Creditbit", symbol: "CRB" },
	{ aliases: [], name: "Ulatech", symbol: "ULA" },
	{ aliases: [], name: "Lunyr", symbol: "LUN" },
	{ aliases: [], name: "Prospectors Gold", symbol: "PGL" },
	{ aliases: [], name: "HempCoin", symbol: "THC" },
	{ aliases: [], name: "Darsek", symbol: "KED" },
	{ aliases: [], name: "Trinity Netwo...", symbol: "TNC" },
	{ aliases: [], name: "Embers", symbol: "MBRS" },
	{ aliases: [], name: "Titcoin", symbol: "TIT" },
	{ aliases: [], name: "Global Jobcoin", symbol: "GJC" },
	{ aliases: [], name: "EarthCoin", symbol: "EAC" },
	{ aliases: [], name: "Olympus Labs", symbol: "MOT" },
	{ aliases: [], name: "EmberCoin", symbol: "EMB" },
	{ aliases: [], name: "KuCoin Shares", symbol: "KCS" },
	{ aliases: [], name: "Melon", symbol: "MLN" },
	{ aliases: [], name: "BoostCoin", symbol: "BOST" },
	{ aliases: [], name: "NVO", symbol: "NVST" },
	{ aliases: [], name: "BitDice", symbol: "CSNO" },
	{ aliases: [], symbol: "SNG" },
	{ aliases: [], name: "Elastic", symbol: "XEL" },
	{ aliases: [], name: "DigiCube", symbol: "CUBE" },
	{ aliases: [], name: "Aerium", symbol: "AERM" },
	{ aliases: [], name: "Fantomcoin", symbol: "FCN" },
	{ aliases: [], name: "Ark", symbol: "ARK" },
	{ aliases: [], name: "DigixDAO", symbol: "DGD" },
	{ aliases: [], name: "GPU Coin", symbol: "GPU" },
	{ aliases: [], name: "BLOCKv", symbol: "VEE" },
	{ aliases: [], name: "LanaCoin", symbol: "LANA" },
	{ aliases: [], name: "Goodomy", symbol: "GOOD" },
	{ aliases: [], name: "DigitalNote", symbol: "XDN" },
	{ aliases: [], name: "Printerium", symbol: "PRX" },
	{ aliases: [], name: "Karbo", symbol: "KRB" },
	{ aliases: [], name: "FujiCoin", symbol: "FJC" },
	{ aliases: [], name: "Quebecoin", symbol: "QBC" },
	{ aliases: [], name: "BTSR", symbol: "BTSR" },
	{ aliases: [], name: "FuzzBalls", symbol: "FUZZ" },
	{ aliases: [], name: "XGOX", symbol: "XGOX" },
	{ aliases: [], name: "BitShares", symbol: "BTS" },
	{ aliases: [], name: "bitJob", symbol: "STU" },
	{ aliases: [], name: "HEROcoin", symbol: "PLAY" },
	{ aliases: [], name: "Sharechain", symbol: "SSS" },
	{ aliases: [], name: "Bread", symbol: "BRD" },
	{ aliases: [], name: "PRCoin", symbol: "PRC" },
	{ aliases: [], name: "G3N", symbol: "G3N" },
	{ aliases: [], name: "Royal Kingdom...", symbol: "RKC" },
	{ aliases: [], name: "CageCoin", symbol: "CAGE" },
	{ aliases: [], symbol: "USD" },
	{ aliases: [], name: "Ammo Reloaded", symbol: "AMMO" },
	{ aliases: [], name: "SaluS", symbol: "SLS" },
	{ aliases: [], name: "NuShares", symbol: "NSR" },
	{ aliases: [], name: "NevaCoin", symbol: "NEVA" },
	{ aliases: [], name: "Energycoin", symbol: "ENRG" },
	{ aliases: [], name: "Populous", symbol: "PPT" },
	{ aliases: [], name: "InflationCoin", symbol: "IFLT" },
	{ aliases: [], name: "Visio", symbol: "VISIO" },
	{ aliases: [], name: "Ixcoin", symbol: "IXC" },
	{ aliases: [], name: "VirtualCoin", symbol: "VC" },
	{ aliases: [], name: "Theta Token", symbol: "THETA" },
	{ aliases: [], name: "FirstBlood", symbol: "1ST" },
	{ aliases: [], name: "RedCoin", symbol: "RED" },
	{ aliases: [], name: "2GIVE", symbol: "2GIVE" },
	{ aliases: [], name: "Digital Rupees", symbol: "DRS" },
	{ aliases: [], name: "Rustbits", symbol: "RUSTBITS" },
	{ aliases: [], name: "BriaCoin", symbol: "BRIA" },
	{ aliases: [], symbol: "RRT" },
	{ aliases: [], name: "JobsCoin", symbol: "JOBS" },
	{ aliases: [], name: "district0x", symbol: "DNT" },
	{ aliases: [], name: "Footy Cash", symbol: "XFT" },
	{ aliases: [], name: "onG.social", symbol: "ONG" },
	{ aliases: [], name: "Internet of P...", symbol: "IOP" },
	{ aliases: [], name: "Halcyon", symbol: "HAL" },
	{ aliases: [], name: "BERNcash", symbol: "BERN" },
	{ aliases: [], name: "Argus", symbol: "ARGUS" },
	{ aliases: [], name: "Bitcoin Cash", symbol: "BCH" },
	{ aliases: [], name: "TrezarCoin", symbol: "TZC" },
	{ aliases: [], name: "LiteBar", symbol: "LTB" },
	{ aliases: [], name: "Tristar Coin", symbol: "TSTR" },
	{ aliases: [], name: "Moin", symbol: "MOIN" },
	{ aliases: [], name: "Neumark", symbol: "NEU" },
	{ aliases: [], name: "Neutron", symbol: "NTRN" },
	{ aliases: [], name: "Artex Coin", symbol: "ATX" },
	{ aliases: [], name: "Rivetz", symbol: "RVT" },
	{ aliases: [], name: "Crypto Bullion", symbol: "CBX" },
	{ aliases: [], name: "Rise", symbol: "RISE" },
	{ aliases: [], name: "TaaS", symbol: "TAAS" },
	{ aliases: [], name: "GeyserCoin", symbol: "GSR" },
	{ aliases: [], name: "OAX", symbol: "OAX" },
	{ aliases: [], name: "Kittehcoin", symbol: "MEOW" },
	{ aliases: [], name: "FirstCoin", symbol: "FRST" },
	{ aliases: [], name: "BlazeCoin", symbol: "BLZ" },
	{ aliases: [], name: "Unobtanium", symbol: "UNO" },
	{ aliases: [], name: "TIES Network", symbol: "TIE" },
	{ aliases: [], name: "Fujinto", symbol: "NTO" },
	{ aliases: [], name: "Nekonium", symbol: "NUKO" },
	{ aliases: [], name: "Allion", symbol: "ALL" },
	{ aliases: [], name: "BioBar", symbol: "BIOB" },
	{ aliases: [], name: "BROTHER", symbol: "BRAT" },
	{ aliases: [], name: "X-Coin", symbol: "XCO" },
	{ aliases: [], name: "HTML5COIN", symbol: "HTML5" },
	{ aliases: [], name: "Bowhead", symbol: "AHT" },
	{ aliases: [], name: "Trollcoin", symbol: "TROLL" },
	{ aliases: [], name: "JavaScript Token", symbol: "JS" },
	{ aliases: [], name: "Ethereum Dark", symbol: "ETHD" },
	{ aliases: [], name: "Enigma", symbol: "XNG" },
	{ aliases: [], name: "Emphy", symbol: "EPY" },
	{ aliases: [], name: "Asch", symbol: "XAS" },
	{ aliases: [], name: "Swing", symbol: "SWING" },
	{ aliases: [], name: "HomeBlockCoin", symbol: "HBC" },
	{ aliases: [], name: "Minereum", symbol: "MNE" },
	{ aliases: [], name: "SmileyCoin", symbol: "SMLY" },
	{ aliases: [], name: "ArcticCoin", symbol: "ARC" },
	{ aliases: [], symbol: "JPY" },
	{ aliases: [], name: "Nxt", symbol: "NXT" },
	{ aliases: [], name: "Aventus", symbol: "AVT" },
	{ aliases: [], name: "Solarflarecoin", symbol: "SFC" },
	{ aliases: [], name: "Happycoin", symbol: "HPC" },
	{ aliases: [], name: "Shift", symbol: "SHIFT" },
	{ aliases: [], name: "AdShares", symbol: "ADST" },
	{ aliases: [], name: "Pascal Coin", symbol: "PASC" },
	{ aliases: [], name: "The ChampCoin", symbol: "TCC" },
	{ aliases: [], name: "Hive", symbol: "HVN" },
	{ aliases: [], name: "Creativecoin", symbol: "CREA" },
	{ aliases: [], name: "Bytom", symbol: "BTM" },
	{ aliases: [], name: "Trade Token", symbol: "TIO" },
	{ aliases: [], symbol: "GBG" },
	{ aliases: [], name: "Coin(O)", symbol: "CNO" },
	{ aliases: [], name: "iEthereum", symbol: "IETH" },
	{ aliases: [], name: "Kin", symbol: "KIN" },
	{ aliases: [], name: "The Cypherfunks", symbol: "FUNK" },
	{ aliases: [], name: "Electroneum", symbol: "ETN" },
	{ aliases: [], name: "Farad", symbol: "FRD" },
	{ aliases: [], name: "GeoCoin", symbol: "GEO" },
	{ aliases: [], name: "SmartCash", symbol: "SMART" },
	{ aliases: [], name: "Mooncoin", symbol: "MOON" },
	{ aliases: [], name: "Mincoin", symbol: "MNC" },
	{ aliases: [], name: "Monster Byte", symbol: "MBI" },
	{ aliases: [], name: "DROXNE", symbol: "DRXNE" },
	{ aliases: [], name: "Augur", symbol: "REP" },
	{ aliases: [], name: "Kore", symbol: "KORE" },
	{ aliases: [], name: "Bitcedi", symbol: "BXC" },
	{ aliases: [], name: "Novacoin", symbol: "NVC" },
	{ aliases: [], name: "Expanse", symbol: "EXP" },
	{ aliases: [], name: "Bitdeal", symbol: "BDL" },
	{ aliases: [], name: "BunnyCoin", symbol: "BUN" },
	{ aliases: [], name: "Bitcoin Red", symbol: "BTCRED" },
	{ aliases: [], name: "Bitzeny", symbol: "ZNY" },
	{ aliases: [], name: "Qvolta", symbol: "QVT" },
	{ aliases: [], name: "Centurion", symbol: "CNT" },
	{ aliases: [], name: "Agrello", symbol: "DLT" },
	{ aliases: [], name: "Miners' Rewar...", symbol: "MRT" },
	{ aliases: [], name: "Boolberry", symbol: "BBR" },
	{ aliases: [], name: "UTRUST", symbol: "UTK" },
	{ aliases: [], name: "Nuls", symbol: "NULS" },
	{ aliases: [], name: "CompuCoin", symbol: "CPN" },
	{ aliases: [], name: "LUXCoin", symbol: "LUX" },
	{ aliases: [], name: "MediBloc", symbol: "MED" },
	{ aliases: [], name: "Sumokoin", symbol: "SUMO" },
	{ aliases: [], name: "GoldPieces", symbol: "GP" },
	{ aliases: [], name: "MonetaryUnit", symbol: "MUE" },
	{ aliases: [], name: "Unrealcoin", symbol: "URC" },
	{ aliases: [], name: "Gnosis", symbol: "GNO" },
	{ aliases: [], name: "LeviarCoin", symbol: "XLC" },
	{ aliases: [], name: "DopeCoin", symbol: "DOPE" },
	{ aliases: [], name: "Octanox", symbol: "OTX" },
	{ aliases: [], name: "Waves Communi...", symbol: "WCT" },
	{ aliases: [], name: "Coimatic 3.0", symbol: "CTIC3" },
	{ aliases: [], name: "Wagerr", symbol: "WGR" },
	{ aliases: [], name: "PlayerCoin", symbol: "PLACO" },
	{ aliases: [], name: "FLiK", symbol: "FLIK" },
	{ aliases: [], name: "Bela", symbol: "BELA" },
	{ aliases: [], name: "Ignis", symbol: "IGNIS" },
	{ aliases: [], name: "FuelCoin", symbol: "FC2" },
	{ aliases: [], name: "PlusCoin", symbol: "PLC" },
	{ aliases: [], name: "DecentBet", symbol: "DBET" },
	{ aliases: [], name: "E4ROW", symbol: "E4ROW" },
	{ aliases: [], name: "BBQCoin", symbol: "BQC" },
	{ aliases: [], name: "EncryptoTel [...", symbol: "ETT" },
	{ aliases: [], name: "Cabbage", symbol: "CAB" },
	{ aliases: [], name: "CryptoEscudo", symbol: "CESC" },
	{ aliases: [], name: "Etheroll", symbol: "DICE" },
	{ aliases: [], name: "Elixir", symbol: "ELIX" },
	{ aliases: [], name: "Synergy", symbol: "SNRG" },
	{ aliases: [], name: "BitQuark", symbol: "BTQ" },
	{ aliases: [], name: "Virtacoinplus", symbol: "XVP" },
	{ aliases: [], name: "NetCoin", symbol: "NET2" },
	{ aliases: [], name: "Onix", symbol: "ONX" },
	{ aliases: [], name: "Kyber Network", symbol: "KNC" },
	{ aliases: [], name: "Senderon", symbol: "SDRN" },
	{ aliases: [], name: "Pluton", symbol: "PLU" },
	{ aliases: [], name: "EGO", symbol: "EGO" },
	{ aliases: [], name: "Skycoin", symbol: "SKY" },
	{ aliases: [], name: "HealthyWormCoin", symbol: "WORM" },
	{ aliases: [], name: "Project-X", symbol: "NANOX" },
	{ aliases: [], name: "BitDegree", symbol: "BDG" },
	{ aliases: [], name: "AudioCoin", symbol: "ADC" },
	{ aliases: [], name: "IOTA", symbol: "IOT" },
	{ aliases: [], name: "Crown", symbol: "CRW" },
	{ aliases: [], name: "Zero", symbol: "ZER" },
	{ aliases: [], name: "Monetha", symbol: "MTH" },
	{ aliases: [], name: "eBitcoinCash", symbol: "EBCH" },
	{ aliases: [], name: "Basic Attenti...", symbol: "BAT" },
	{ aliases: [], name: "Elementrem", symbol: "ELE" },
	{ aliases: [], name: "Primas", symbol: "PST" },
	{ aliases: [], name: "PIECoin", symbol: "PIE" },
	{ aliases: [], name: "Antilitecoin", symbol: "ALTC" },
	{ aliases: [], symbol: "CLUB" },
	{ aliases: [], name: "LEOcoin", symbol: "LEO" },
	{ aliases: [], name: "SydPak", symbol: "SDP" },
	{ aliases: [], name: "EverGreenCoin", symbol: "EGC" },
	{ aliases: [], name: "Bitstar", symbol: "BITS" },
	{ aliases: [], name: "SmartBillions", symbol: "SMART2" },
	{ aliases: [], name: "Golos", symbol: "GOLOS" },
	{ aliases: [], name: "PIVX", symbol: "PIVX" },
	{ aliases: [], name: "Bodhi", symbol: "BOT" },
	{ aliases: [], name: "Yellow Token", symbol: "YEL" },
	{ aliases: [], name: "Tracto", symbol: "TRCT" },
	{ aliases: [], name: "SatoshiMadness", symbol: "MAD" },
	{ aliases: [], name: "SmartCoin", symbol: "SMC" },
	{ aliases: [], symbol: "AID" },
	{ aliases: [], name: "WAX", symbol: "WAX" },
	{ aliases: [], name: "Confido", symbol: "CFD" },
	{ aliases: [], name: "Californium", symbol: "CF" },
	{ aliases: [], name: "Abjcoin", symbol: "ABJ" },
	{ aliases: [], name: "Bitswift", symbol: "SWIFT" },
	{ aliases: [], name: "Argentum", symbol: "ARG" },
	{ aliases: [], name: "IoT Chain", symbol: "ITC" },
	{ aliases: [], name: "Opal", symbol: "OPAL" },
	{ aliases: [], name: "Denarius", symbol: "DNR" },
	{ aliases: [], name: "CrevaCoin", symbol: "CREVA" },
	{ aliases: [], name: "AirSwap", symbol: "AST" },
	{ aliases: [], name: "High Voltage", symbol: "HVCO" },
	{ aliases: [], name: "MazaCoin", symbol: "MZC" },
	{ aliases: [], name: "P7Coin", symbol: "P7C" },
	{ aliases: [], name: "Innova", symbol: "INN" },
	{ aliases: [], name: "Wings", symbol: "WINGS" },
	{ aliases: [], name: "Ripto Bux", symbol: "RBX" },
	{ aliases: [], name: "020LondonCoin", symbol: "020" },
	{ aliases: [], name: "Smart Investm...", symbol: "SIFT" },
	{ aliases: [], name: "Tokes", symbol: "TKS" },
	{ aliases: [], name: "Counterparty", symbol: "XCP" },
	{ aliases: [], name: "Synereo", symbol: "AMP" },
	{ aliases: [], name: "FUNCoin", symbol: "FUNC" },
	{ aliases: [], name: "Autonio", symbol: "NIO" },
	{ aliases: [], name: "Particl", symbol: "PART" },
	{ aliases: [], name: "I/O Coin", symbol: "IOC" },
	{ aliases: [], name: "ZenCash", symbol: "ZEN" },
	{ aliases: [], name: "CannabisCoin", symbol: "CANN" },
	{ aliases: [], name: "WandX", symbol: "WAND" },
	{ aliases: [], name: "TrueFlip", symbol: "TFL" },
	{ aliases: [], name: "SHIELD", symbol: "XSH" },
	{ aliases: [], name: "MACRON", symbol: "MCRN" },
	{ aliases: [], name: "Simple Token", symbol: "OST" },
	{ aliases: [], name: "Legends Room", symbol: "LGD" },
	{ aliases: [], name: "ChanCoin", symbol: "4CHN" },
	{ aliases: [], name: "BitSend", symbol: "BSD" },
	{ aliases: [], name: "Block Array", symbol: "ARY" },
	{ aliases: [], name: "Ethereum Cash", symbol: "ECASH" },
	{ aliases: [], name: "Chronos", symbol: "CRX" },
	{ aliases: [], name: "CaliphCoin", symbol: "CALC" },
	{ aliases: [], name: "Pylon Network", symbol: "PYLNT" },
	{ aliases: [], name: "Atomic Coin", symbol: "ATOM" },
	{ aliases: [], name: "Incent", symbol: "INCNT" },
	{ aliases: [], name: "Nimiq", symbol: "NET" },
	{ aliases: [], name: "Cthulhu Offer...", symbol: "OFF" },
	{ aliases: [], name: "Breakout Stake", symbol: "BRX" },
	{ aliases: [], name: "Qtum", symbol: "QTUM" },
	{ aliases: [], name: "AsiaCoin", symbol: "AC" },
	{ aliases: [], name: "Chronobank", symbol: "TIME" },
	{ aliases: [], name: "SunContract", symbol: "SNC" },
	{ aliases: [], name: "ICOS", symbol: "ICOS" },
	{ aliases: [], name: "Bolivarcoin", symbol: "BOLI" },
	{ aliases: [], name: "Metal Music Coin", symbol: "MTLMC3" },
	{ aliases: [], name: "Luna Coin", symbol: "LUNA" },
	{ aliases: [], name: "Worldcore", symbol: "WRC" },
	{ aliases: [], name: "Newbium", symbol: "NEWB" },
	{ aliases: [], name: "Zeusshield", symbol: "ZSC" },
	{ aliases: [], name: "Abncoin", symbol: "ABN" },
	{ aliases: [], name: "Status", symbol: "SNT" }
];
